### ISSUE TITLE
Perl strings are different from C strings

### ISSUE THREAD

**Issue by chansen** [dnmfarrell/URI-Encode-XS#2]
C strings use the null character as a sentinel value for indicating the end of a string. Perl strings can contain anything, including the null character.

``` perl
is(uri_encode("ABC\x00DEF"), "ABC%00DEF", 'constains encoded null character');
is(uri_decode("ABC%00DEF"), "ABC\x00DEF", 'constains decoded null character');
```

**Comment by dnmfarrell** [comment]
interesting, thanks!

**Comment by chansen** [comment]
I have forked your repro and added support for encoded and decoded null's. I 
also took the opportunity to make the code portable and to optimize it.

Before:

```
            Rate escape encode
escape  126834/s     --   -97%
encode 4079234/s  3116%     --
              Rate unescape   decode
unescape  176202/s       --     -97%
decode   6609805/s    3651%       --
```

After:

```
             Rate escape encode
escape   121459/s     --   -99%
encode 11086334/s  9028%     --
              Rate unescape   decode
unescape  172863/s       --     -98%
decode   9847069/s    5596%       --
```

https://github.com/chansen/URI-Encode-XS/tree/miscellaneous

If you want I could make a pull request or you can just cherry pick the commits
you want.

There is still a few issues:

1) `uri_encode()` and `uri_decode()` should enforce octets and `croak()` if given a
string containing code points above U+00FF.

2) IMO `uri_encode()` and `uri_decode()` should not `croak()` if given an empty string

3) `say uri_decode("AB%4%44")`
`AB44`

**Comment by dnmfarrell** [comment]
Woah, this is incredible! What is this black magic?! :+1:

**Comment by dnmfarrell** [comment]
I merged all of your commits, thanks a lot - I appreciate it. I'll create tickets for the issues you mentioned.
