### ISSUE TITLE
`uri_decode` should handle invalid sequences correctly

### ISSUE THREAD

**Issue by dnmfarrell** [dnmfarrell/URI-Encode-XS#5]
Currently:

```
say uri_decode("AB%4%44")
AB44
```

But I _think_ it should be:

```
say uri_decode("AB%4%44")
ABD
```

Or maybe:

```
say uri_decode("AB%4%44")
AB4D
```

**Comment by chansen** [comment]
I think it's better to just copy the broken PCT encoded octet, eg:

```
say uri_decode("AB%4%44")
AB%4D

```

We could also implement a strict version (croaks if encounter a broken PCT encoded octet) and a lenient version which just copies the broken PCT encoded octet.

Perhaps: 
`uri_decode($octets, lenient => 1);`

Or if the lenient version is the default:
`uri_decode($octets, strict => 1);`

**Comment by dnmfarrell** [comment]
Oh yeah I like it. Commit `df8009e9d7af4cf243fa29ca8aaa23982feeba58` implements a lenient version
