### ISSUE TITLE
Add utf8 methods

### ISSUE THREAD

**Issue by dnmfarrell** [dnmfarrell/URI-Encode-XS#9]
Right now we croak on utf88 multi-byte characters that don't fit into a byte. I _think_ we can add `uri_encode_utf8` and `uri_decode_utf8` methods which as almost the same as the current versions, except we remove the utf8 block:

```
    if (SvUTF8(uri))
    {   
      /* make a temp copy */
      uri = sv_2mortal(newSVpvn(src, len));

      /* turn on the utf8 flag */
      SvUTF8_on(uri);

      /* if any of the characters don't fit into an octet ... */
      if (!sv_utf8_downgrade(uri, TRUE))
          croak("Wide character in octet string");

      /* copy the SV */
      src = SvPV_const(uri, len);
    }
```

And we'd need to set the UTF8 flag on the SV so that the returned scalar behaves as expected in Perl space. Am I missing anything else?

**Comment by dnmfarrell** [comment]
Maybe a better way to do it would be to include an options hashref:

```
uri_encode($string, { utf8 => 1});
```

That way we could add other options like strict mode per #5 .

**Comment by chansen** [comment]
I'll provide a pull request for these features, uri_encode_utf8() and uri_decode_utf8().

**Comment by dnmfarrell** [comment]
Hey @chansen thank you :)
What do you think about an options hashref? That would let us support a strict mode, utf8, maybe an "unreserved" vs "reserved" mode etc.

**Comment by chansen** [comment]
I don't think passing a hash reference is a good idea from a performance POV, a list with named parameters would be better. How about:

```
   $octets = uri_decode($octets [, strict => false]);
   $octets = uri_encode($octets [, set => 'unreserved']);
   $string = uri_decode_utf8($octets [, strict => false]);
   $octets = uri_encode_utf8($string [, set => 'unreserved']);
```

Where `set` would specify the character set to use. We could implement named set's for all components of the URI.

```
say uri_encode_utf8("/I/like/☕", set => 'path');
I/like/%E2%98%95
```

**Comment by dnmfarrell** [comment]
Ah interesting, ok let's avoid the hashref option. I like your version, let's do it!
